=== ISS-Boy/MH/MParser/src/main/resources/monitor/Monitor.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- 仪表板 -->
    <xs:complexType name="PanelType">
        <xs:all>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="metrics" type="xs:string"/>
            <xs:element name="filter" type="xs:string"/>
            <xs:element name="group" type="xs:string"/>
        </xs:all>
        <xs:attribute name="query_id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>

    <!-- kafka连接 -->
    <xs:complexType name="KafkaConnectionType">
        <xs:sequence>
            <xs:element name="bootstrap_server" type="xs:string"/>
            <xs:element name="schema_registry" type="xs:string"/>
            <xs:element name="application_id" type="xs:string"/>
            <xs:element name="key_serializer" type="xs:string"/>
            <xs:element name="key_deserializer" type="xs:string"/>
            <xs:element name="value_serializer" type="xs:string"/>
            <xs:element name="value_deserializer" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- ElasticSearch连接 -->
    <xs:complexType name="ElasticSearchConnection">
        <xs:sequence>
            <xs:element name="ip" type="xs:string" />
            <xs:element name="index" type="xs:string" />
            <xs:element name="type" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <!-- Opentsdb连接 -->
    <xs:complexType name="OpentsdbConnection">
        <xs:sequence>
            <xs:element name="ip" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- grafana连接 -->
    <xs:complexType name="GrafanaConnection">
        <xs:sequence>
            <xs:element name="ip" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- 模式实例 -->
    <xs:complexType name="PatternType">
        <xs:sequence>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="method" type="xs:string"/>
            <xs:element name="characteristic" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>

    <!-- 目标数据类型 -->
    <xs:simpleType name="DataTypeRestriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="synthea" />
            <xs:enumeration value="mhealth" />
            <xs:enumeration value="hybrid" />
        </xs:restriction>
    </xs:simpleType>

    <!-- 数据描述 -->
    <xs:complexType name="DataDescription">
        <xs:sequence>
            <xs:element name="datatype">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="synthea" />
                        <xs:enumeration value="mhealth" />
                        <xs:enumeration value="hybrid" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="structure" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <!-- 连接类型 -->
    <xs:complexType name="JoinType">
        <xs:sequence minOccurs="0">
            <xs:element name="join_type" >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Dynamic-Join-Dynamic" />
                        <xs:enumeration value="Dynamic-Join-Static" />
                        <xs:enumeration value="Static-Join-Static" />
                        <xs:enumeration value="Other" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="join_targets">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="target" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:all>
                                    <xs:element name="id" type="xs:unsignedInt" />
                                    <xs:element name="left" type="xs:string" />
                                    <xs:element name="right" type="xs:string" />
                                    <xs:element name="join_type" type="xs:string" />
                                    <xs:element name="source" type="xs:string" />
                                    <xs:element name="condition" type="xs:string" />
                                </xs:all>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- 分组类型 -->
    <xs:complexType name="GroupType">
        <xs:sequence minOccurs="0">
            <xs:element name="groups">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="having" type="xs:string" />
            <xs:element name="condition" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <!-- 选择投影描述 -->
    <xs:complexType name="SelectType">
        <xs:sequence minOccurs="0">
            <xs:element name="selects">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="distinct" type="xs:boolean" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- 窗口描述 -->
    <xs:complexType name="WindowType">
        <xs:sequence minOccurs="0">
            <xs:element name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="tumbling" />
                        <xs:enumeration value="hopping" />
                        <xs:enumeration value="sliding" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="window_length" type="xs:string" />
            <xs:element name="window_interval" type="xs:unsignedInt" />
        </xs:sequence>
    </xs:complexType>

    <!-- 增幅增比描述 -->
    <xs:complexType name="GrowthType">
        <xs:sequence minOccurs="0">
            <xs:element name="calculation_interval" type="xs:unsignedInt" />
        </xs:sequence>
    </xs:complexType>

    <!-- 聚集描述 -->
    <xs:complexType name="AggregationType">
        <xs:sequence minOccurs="0">
            <xs:element name="aggregation_values">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType mixed="true">
                                <xs:attribute name="aggregation_type" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="count"/>
                                            <xs:enumeration value="average"/>
                                            <xs:enumeration value="max"/>
                                            <xs:enumeration value="min"/>
                                            <xs:enumeration value="sum"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- 过滤描述 -->
    <xs:complexType name="FilterType">
        <xs:sequence minOccurs="0">
            <xs:element name="filters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="filter" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="value" type="xs:string"/>
                                    <xs:element name="op">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="LT" />
                                                <xs:enumeration value="LQ" />
                                                <xs:enumeration value="ST" />
                                                <xs:enumeration value="SQ" />
                                                <xs:enumeration value="EQ" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="threhold" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>

                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- 特征描述 -->
    <xs:complexType name="CharacteristicType">
        <xs:sequence minOccurs="0">
            <xs:element name="characteristic">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="pattern_id" type="xs:unsignedInt" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- 操作描述 -->
    <xs:complexType name="OperationDescription">
        <xs:sequence>
            <xs:element name="join" type="JoinType" />
            <xs:element name="group" type="GroupType" />
            <xs:element name="select" type="SelectType" />
            <xs:element name="window" type="WindowType" />
            <xs:element name="growth" type="GrowthType" />
            <xs:element name="aggregation" type="AggregationType" />
            <xs:element name="filter" type="FilterType" />
            <xs:element name="characteristic" type="CharacteristicType" />
        </xs:sequence>
    </xs:complexType>

    <!-- monitor总体结构 -->
    <xs:element name="monitor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datasource">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="kafka">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="connection" type="KafkaConnectionType" />
                                        <xs:element name="datasink" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="elasticsearch">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="connection" type="ElasticSearchConnection"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="opentsdb">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="connection" type="OpentsdbConnection"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="grafana">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="connection" type="GrafanaConnection"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dashboard">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="panels">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="panel" minOccurs="0" maxOccurs="unbounded" type="PanelType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pattern">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pattern_lib">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="instance" type="PatternType" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="monitor-queries">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="query" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="target" type="DataDescription" />
                                        <xs:element name="operation" type="OperationDescription" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ISS-Boy/MH/MParser/src/main/resources/monitor/MonitorExample.xml
<?xml version="1.0" encoding="UTF-8" ?>
<monitor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="/monitor/Monitor.xsd">
    <datasource>
        <kafka>
            <connection>
                <bootstrap_server>192.168.222.226:9092</bootstrap_server>
                <schema_registry>http://192.168.222.226:8081</schema_registry>
                <application_id>application-test</application_id>
                <key_serializer>String</key_serializer>
                <key_deserializer>String</key_deserializer>
                <value_serializer>AVRO</value_serializer>
                <value_deserializer>AVRO</value_deserializer>
            </connection>
            <datasink>opentsdb</datasink>
        </kafka>
        <elasticsearch>
            <connection>
                <ip>192.168.222.232:9200</ip>
                <index>synthea</index>
                <type>sythnea</type>
            </connection>
        </elasticsearch>
        <opentsdb>
            <connection>
                <ip>172.16.17.177:3000</ip>
            </connection>
        </opentsdb>
        <grafana>
            <connection>
                <ip>192.168.222.232:3000</ip>
            </connection>
        </grafana>
    </datasource>
    <dashboard>
        <panels>
            <panel query_id="1">
                <type></type>
                <metrics></metrics>
                <filter></filter>
                <group></group>
            </panel>
        </panels>
    </dashboard>
    <pattern>
        <pattern_lib />
    </pattern>
    <monitor-queries>
        <query id="1">
            <target>
                <datatype>mhealth</datatype>
                <structure>{"header":{"id":"21672706-a52c-4d8e-8fbd-982acad98ca4","schema_id":{"namespace":"omh","name":"blood-pressure","version":"1.0"},"user_id":"the-user-6240"},"body":{"effective_time_frame":{"date_time":"2017-01-01T12:02:25Z"},"systolic_blood_pressure":{"unit":"mmHg","value":111.5894042161057},"diastolic_blood_pressure":{"unit":"mmHg","value":67.71621292933139}}}
                </structure>
            </target>
            <operation>
                <join>
                    <join_type>Dynamic-Join-Dynamic</join_type>
                    <join_targets>
                        <target>
                            <id>1</id>
                            <left>heart-rate</left>
                            <right>blood-pressure</right>
                            <join_type>inner</join_type>
                            <source>mhealth</source>
                            <condition>user-id</condition>
                        </target>
                    </join_targets>
                </join>

                <group />

                <select />

                <window/>

                <growth />

                <aggregation />
                <filter>
                    <filters>
                        <filter>
                            <value>heart_rate</value>
                            <op>LQ</op>
                            <threhold>120</threhold>
                        </filter>
                        <filter>
                            <value>systolic_blood_pressure</value>
                            <op>LQ</op>
                            <threhold>180</threhold>
                        </filter>
                    </filters>
                </filter>
                <characteristic>
                    <characteristic />
                </characteristic>
            </operation>
        </query>
    </monitor-queries>
</monitor>
